PeConfortavelLtda/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='index.html'), name = 'index'),
    path('produtos/', include('produtos.urls', namespace= 'produtos')),
    path('clientes/', include('clientes.urls', namespace= 'clientes')),
    path('fabricantes/', include('fabricantes.urls', namespace= 'fabricantes')),
    path('venda/', include('venda.urls', namespace= 'venda')),
    path('login/', include('login.urls', namespace= 'login')),
    path('contato/', include('contato.urls', namespace= 'contatos')),
]

fabricantes/urls.py
from django.urls import path

from . import views

app_name = "fabricantes"

urlpatterns = [
    path('lista', views.listar, name='listar'),
    path('cadastro', views.cadastro, name='cadastro'),
    path('cadastra', views.cadastrar, name='cadastrar'),
    path('excluir/<int:codigo>', views.excluir, name='excluir_fabricantes'),
    path('carregar_fabricantes/<int:codigo>', views.carregar_fabricantes, name='carregar_fabricantes'),
    path('atualizar_fabricante/', views.atualizar, name='atualizar_fabricante'),
]

login/urls.py
from django.urls import path

from . import views

app_name = "login"

urlpatterns = [
    path('login', views.login, name='login'),
]

fabricantes/models.py
from django.db import models

# Create your models here.

class Fabricantes(models.Model):
    codigo = models.AutoField(primary_key=True, 
                           help_text='Codigo do fornecedor')
    nome = models.CharField(max_length=70, 
                            help_text='Nome do fornecedor')
    
    def __str__(self):
        return f'{self.codigo} - {self.nome}'

fabricantes/forms.py
from django import forms


class FabricantesForm(forms.Form):
    nome = forms.CharField(max_length=70, 
                            help_text='Nome do fornecedor')
    
class FabricantesAtualizarForm(forms.Form):
    codigo = forms.IntegerField( 
                           help_text='Codigo do fornecedor')
    nome = forms.CharField(max_length=70, 
                            help_text='Nome do fornecedor')
    

fabricantes/views.py
from django.shortcuts import render, redirect
from fabricantes.models import Fabricantes
from fabricantes.forms import FabricantesForm, FabricantesAtualizarForm

# Create your views here.

def listar(request):
    lista_fabricantes = Fabricantes.objects.all()
    contexto = {
        'fabricantes': lista_fabricantes,
    }
    return render(request, 'fabricantes/listarFabricantes.html', context=contexto)

def cadastro(request):
    return render(request, 'fabricantes/cadastroFabricantes.html')

def cadastrar(request):
    form = FabricantesForm(request.POST)
    if form.is_valid():
        dados_fabricante = form.cleaned_data
        fabricante = Fabricantes(
            nome=dados_fabricante['nome'],
        )
        fabricante.save()
    return render(request, 'fabricantes/cadastroFabricantes.html')

def excluir(request, codigo):
    fabricante = Fabricantes.objects.get(pk=codigo)
    fabricante.delete()
    return redirect('fabricantes:listar')

def carregar_fabricantes(request, codigo):
    fabricante = Fabricantes.objects.get(pk=codigo)
    contexto = {
        'fabricante': fabricante,
    }
    return render(request, 'fabricantes/atualizarFabricantes.html', context=contexto)

def atualizar(request):
    if request.method == 'POST':
        form = FabricantesAtualizarForm(request.POST)
        if form.is_valid():
            dados_fabricante = form.cleaned_data
            codigo = dados_fabricante['codigo']

            fabricante = Fabricantes.objects.get(pk=codigo)
            fabricante.nome = dados_fabricante['nome']
            fabricante.save()
        else:
            print(form.errors)
    return redirect('fabricantes:listar')

fabricantes/templates/fabricantes/cadastroFabricantes.html
{% extends "base.html" %}
{% load static %}

    {% block title %}
        <title>Pé Confortavel</title>
    {% endblock %}



        {% block menu %}
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container">
                <a class="navbar-brand" href="/">Pé Confortável Ltda.</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item"><a class="nav-link" href="{% url 'fabricantes:cadastro' %}">Cadastro</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'fabricantes:listar' %}">Listar</a></li>
        
        
        
                    </ul>
                    <ul class="navbar-nav">
                        <li class="nav-item"><a class="nav-link" href="{% url 'login:login' %}">Login</a></li>
                    </ul>
                </div>
            </div>
        </nav>

        {%  endblock %}

        {% block corpo %}
        <main class="container m-2 w-75 mx-auto my-font-family">

    <div class="hero">
        <div class="col text-center m-0">
            <h1 class="mt-2 mb-5 my-h2">Cadastro de Fornecedores</h1>
        </div>
    </div>

    <!-- formulario HTML -->
    <section class="hero">
    <form name="frmCadastrar" action="{% url 'fabricantes:cadastrar' %}" method="post" class="my-label-color-purple">
    {% csrf_token %}

    
        <div>
            <label for="idTxtNome" class="form-label">nome</label>
            <input class="form-control" type="text" id="idTxtNome" name="nome" 
                   placeholder="Informe o nome" maxlength="11" required>
        </div>
    

    <div class="row mt-4">
        <div class="col-12 text-center">
            <button type="reset" class="btn btn-outline-secondary me-2">Limpar</button>
            <button type="submit" class="btn btn-primary">Cadastrar</button>
        </div>
    </div>
</form>
    </section>

        {% endblock %}

fabricantes/templates/fabricantes/listarFabricantes.html
{% extends "base.html" %}
{% load static %}

    {% block title %}
        <title>Pé Confortavel</title>
    {% endblock %}



        {% block menu %}
            <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
                <div class="container">
                    <a class="navbar-brand" href="/">Pé Confortável Ltda.</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarNav">
                        <ul class="navbar-nav me-auto">
                            <li class="nav-item"><a class="nav-link" href="{% url 'fabricantes:cadastro' %}">Cadastro</a></li>
                            <li class="nav-item"><a class="nav-link" href="{% url 'fabricantes:listar' %}">Listar</a></li>
            
            
            
                        </ul>
                        <ul class="navbar-nav">
                            <li class="nav-item"><a class="nav-link" href="{% url 'login:login' %}">Login</a></li>
                        </ul>
                    </div>
                </div>
            </nav>
    
        {%  endblock %}

            
        {% block titulo_pagina %}
        
        
        {% endblock %}

    

    
    
{% block corpo %}
    <main class="container px-0 mx-auto my-font-family">

    <div class="row">
        <div class="col text-center m-0">
            <h1  class="hero">Lista de fabricantes</h1>
        </div>
    </div>

{% if fabricantes %}

    <section class="hero">
    <div class="table-responsive">

        <!-- classes para tabela (Bootstrap) , tabela sem borda, conteudo alinhado ao centro, ... , width: auto -->
        <table class="table
                    table-borderless
                    text-center
                    my-table-hover
                    my-table-image
                    my-table-td-first-child
                    my-table-border-bottom
                    my-table-th
                    w-100">

            <!-- cabecalho -->
            <thead>
                <!-- linhas -->
                <tr>
                    <!-- colunas cabecalho -->
                    <th>codigo</th>
                    <th>Nome</th>
                </tr>
            </thead>

            <!-- linhas -->
            {% for fabricantes in fabricantes %}
                <tr>
                    <td> {{ fabricantes.codigo }} </td>
                    <td> {{ fabricantes.nome }} </td>
                    <td>
                        <a href="{% url 'fabricantes:carregar_fabricantes' fabricantes.codigo %}" class="btn btn-mini"><i class="far fa-edit"></i></a> 
                        <button type="button" class="btn" role="button" data-target="#modalExcluirfabricantes"
                                data-toggle="modal"  
                                data-nome="{{ fabricantes.nome }}" 
                                data-url="{% url 'fabricantes:excluir_fabricantes' fabricantes.codigo %}">
                            <i class="far fa-trash-alt"></i>
                        </button>
                    </td>
                </tr>
            {% endfor %}
        </table>

        </div>
    {% else %}
        <div class="text-danger">
            <p>Não há títulos cadastrados</p>
        </div>
    {% endif %}
</section>


</main>

<div class="modal fade" id="modalExcluirfabricantes" role="dialog" aria-labelledby="Confirmação" aria-hidden="true">

    <div class="modal-dialog modal-dialog-centered">
        
        <div class="modal-content">

            <div class="modal-header">
                <h5 class="modal-title" id="modalLabel">Confirmação</h5>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>

            <div class="modal-body">
                <p id="mensagemExclusao"></p>
            </div>

            <div class="modal-footer">
                <button type="button" class="btn btn-outline-dark" data-dismiss="modal">Cancelar</button>
                <button type="button" class="btn btn-primary" id="btnExcluir">Excluir</button>
            </div>

        </div>

    </div>
</div>
{% endblock %}

{% block javascript_complementar %}

<!-- Prepara o modal com os dados da imagem do Titulo a ser excluido -->
<script type="text/javascript">
    $(document).ready(function() {
        $('#modalExcluirfabricantes').on('show.bs.modal', function(event) {
            var nome = $(event.relatedTarget).data('nome');
            var urlExcluir = $(event.relatedTarget).data('url');
            $("#mensagemExclusao").text("fabricantes [ " + nome + "  ]?");

            $.fn.excluirTitulo = function() {
                var url = $(event.relatedTarget).data('url');
                location.replace(url);
            }
        });
    
        $("#btnExcluir").on('click', function() {
            $.fn.excluirTitulo();
            return false;
        });            
    });
</script>

{% endblock %}